name: Run V4 tests
on:
  pull_request:
    paths:
      - "v4/*"
  push:
    paths:
      - "v4/*"

jobs:
  test:
    name: Test v4 plugins
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        id: tests
        env:
          TRAVIS: yes
        run: ./scripts/test.sh v4

      - name: Notify of test failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: build
          SLACK_COLOR: "#BF280A"
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: V4 Tests Failed
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
